# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import print_pb2 as proto_dot_print__pb2
from proto import print_service_pb2 as proto_dot_print__service__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/print_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VirtualPrinterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitPrintJob = channel.unary_unary(
                '/printer.VirtualPrinter/SubmitPrintJob',
                request_serializer=proto_dot_print__pb2.PrintDocument.SerializeToString,
                response_deserializer=proto_dot_print__pb2.PrintJob.FromString,
                _registered_method=True)
        self.GetJobStatus = channel.unary_unary(
                '/printer.VirtualPrinter/GetJobStatus',
                request_serializer=proto_dot_print__service__pb2.GetJobStatusRequest.SerializeToString,
                response_deserializer=proto_dot_print__pb2.PrintJob.FromString,
                _registered_method=True)
        self.CancelPrintJob = channel.unary_unary(
                '/printer.VirtualPrinter/CancelPrintJob',
                request_serializer=proto_dot_print__service__pb2.CancelJobRequest.SerializeToString,
                response_deserializer=proto_dot_print__pb2.PrintJob.FromString,
                _registered_method=True)
        self.MonitorPrintJob = channel.unary_stream(
                '/printer.VirtualPrinter/MonitorPrintJob',
                request_serializer=proto_dot_print__service__pb2.GetJobStatusRequest.SerializeToString,
                response_deserializer=proto_dot_print__pb2.PrintJob.FromString,
                _registered_method=True)
        self.ListPrintJobs = channel.unary_unary(
                '/printer.VirtualPrinter/ListPrintJobs',
                request_serializer=proto_dot_print__service__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_print__service__pb2.ListPrintJobsResponse.FromString,
                _registered_method=True)


class VirtualPrinterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubmitPrintJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelPrintJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MonitorPrintJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPrintJobs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VirtualPrinterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitPrintJob': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitPrintJob,
                    request_deserializer=proto_dot_print__pb2.PrintDocument.FromString,
                    response_serializer=proto_dot_print__pb2.PrintJob.SerializeToString,
            ),
            'GetJobStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobStatus,
                    request_deserializer=proto_dot_print__service__pb2.GetJobStatusRequest.FromString,
                    response_serializer=proto_dot_print__pb2.PrintJob.SerializeToString,
            ),
            'CancelPrintJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelPrintJob,
                    request_deserializer=proto_dot_print__service__pb2.CancelJobRequest.FromString,
                    response_serializer=proto_dot_print__pb2.PrintJob.SerializeToString,
            ),
            'MonitorPrintJob': grpc.unary_stream_rpc_method_handler(
                    servicer.MonitorPrintJob,
                    request_deserializer=proto_dot_print__service__pb2.GetJobStatusRequest.FromString,
                    response_serializer=proto_dot_print__pb2.PrintJob.SerializeToString,
            ),
            'ListPrintJobs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPrintJobs,
                    request_deserializer=proto_dot_print__service__pb2.Empty.FromString,
                    response_serializer=proto_dot_print__service__pb2.ListPrintJobsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'printer.VirtualPrinter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('printer.VirtualPrinter', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VirtualPrinter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubmitPrintJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/printer.VirtualPrinter/SubmitPrintJob',
            proto_dot_print__pb2.PrintDocument.SerializeToString,
            proto_dot_print__pb2.PrintJob.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJobStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/printer.VirtualPrinter/GetJobStatus',
            proto_dot_print__service__pb2.GetJobStatusRequest.SerializeToString,
            proto_dot_print__pb2.PrintJob.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelPrintJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/printer.VirtualPrinter/CancelPrintJob',
            proto_dot_print__service__pb2.CancelJobRequest.SerializeToString,
            proto_dot_print__pb2.PrintJob.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MonitorPrintJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/printer.VirtualPrinter/MonitorPrintJob',
            proto_dot_print__service__pb2.GetJobStatusRequest.SerializeToString,
            proto_dot_print__pb2.PrintJob.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPrintJobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/printer.VirtualPrinter/ListPrintJobs',
            proto_dot_print__service__pb2.Empty.SerializeToString,
            proto_dot_print__service__pb2.ListPrintJobsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
